name: noul_batmainton
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  pinput: ^4.0.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/iconSvg/
    - assets/icons/iconPng/
  fonts:
    - family: NotoSansLao
      fonts:
        - asset: assets/fonts/NotoSansLaoBold.ttf
        - asset: assets/fonts/NotoSansLaoRegular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoBold.ttf
        - asset: assets/fonts/RobotoRegular.ttf

